/**
 * Generates `app/assets/icons.ts` from every `i-lucide-*` / `i-simple-icons-*`
 * reference found in the source tree.
 *
 * The site ships its icons as inline SVG markup, so no icon runtime, web font
 * or third-party icon CDN is needed at runtime. Icon geometry comes from the
 * @iconify-json packages that are already installed in the workspace.
 *
 * Usage: node scripts/generate-icons.mjs
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, extname } from 'node:path'

const SOURCE_DIR = 'app'
const OUTPUT_FILE = 'app/assets/icons.ts'
const SCAN_EXTENSIONS = new Set(['.vue', '.ts', '.js'])
const ICON_PATTERN = /i-(?:lucide|simple-icons)-[a-z0-9-]+/g

const collections = {
  'i-lucide-': JSON.parse(readFileSync('node_modules/@iconify-json/lucide/icons.json', 'utf8')),
  'i-simple-icons-': JSON.parse(readFileSync('node_modules/@iconify-json/simple-icons/icons.json', 'utf8'))
}

function walk(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      walk(full, files)
    } else if (SCAN_EXTENSIONS.has(extname(entry))) {
      files.push(full)
    }
  }
  return files
}

function collectIconNames() {
  const names = new Set()
  for (const file of walk(SOURCE_DIR)) {
    const source = readFileSync(file, 'utf8')
    for (const match of source.matchAll(ICON_PATTERN)) {
      names.add(match[0])
    }
  }
  return [...names].sort()
}

function resolveBody(collection, iconName) {
  const icon = collection.icons[iconName]
  if (icon) {
    return icon.body
  }
  const alias = collection.aliases?.[iconName]
  if (alias?.parent) {
    return collection.icons[alias.parent]?.body
  }
  return undefined
}

const missing = []
const entries = []

for (const name of collectIconNames()) {
  const prefix = Object.keys(collections).find(candidate => name.startsWith(candidate))
  const body = prefix ? resolveBody(collections[prefix], name.slice(prefix.length)) : undefined
  if (!body) {
    missing.push(name)
    continue
  }
  entries.push(`  '${name}': '${body.replace(/\\/g, '\\\\').replace(/'/g, '\\\'')}'`)
}

if (missing.length > 0) {
  console.error(`✗ Unknown icons: ${missing.join(', ')}`)
  process.exit(1)
}

const output = `/**
 * AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
 * Run \`node scripts/generate-icons.mjs\` after adding or removing an icon.
 *
 * Inline SVG bodies for every icon used in the app (viewBox 0 0 24 24).
 */
export const iconBodies: Record<string, string> = {
${entries.join(',\n')}
}
`

writeFileSync(OUTPUT_FILE, output)
console.log(`✓ ${entries.length} icons written to ${OUTPUT_FILE}`)
